void setupStepper();
void rotateStepperWhile(bool (*isKeepRotating)(),int (*getSpeed)(),bool (*isPositiveDirection)());
float GetCurrentAngle();
void setup_ICM20948();
float getYaw();
void setupButtons();
bool IsLeftPedalOn();
bool IsRightPedalOn();
bool IsPedals();
bool IsBothPedals();
bool IsAutoSearch();
bool IsKeepDirection();
float GetSpeed();
float GetAngle();
